### ISSUE TITLE
"Don't push the button" - warn users not to submit jobs with an RP's keys

### ISSUE THREAD

**Issue by Zorlin** [bacalhau-project/lilypad-docs#23]
Submitting a job with the same keys (pub/priv) as a resource provider on the network causes that resource provider to freak out a bit of it is the one that gets that job.

Basically, if you run a Lilypad RP, when running the Lilypad client you should use separate keys instead of reusing a wallet from the RP.

Nees to update the run a node docs to reflect this, more succinctly.

**Comment by lukemarsden** [comment]
done in https://github.com/bacalhau-project/lilypad-docs/commit/1f81ed28a7795ecd219c3d8972c16ce4bcd7aea3
